### ISSUE TITLE
update instructions according to new sourcemeter version (screenshot is out of date and can be confusing)

### ISSUE THREAD

**Issue by atrautsch** [smartshark/mecoSHARK#5]

**Comment by sherbold** [comment]
please remove --process-dependency-links from documentation when this is done

**Comment by sherbold** [comment]
should be updated once sourcemeter is replaced with OSA

**Comment by patrickneubauer** [comment]
can you please confirm which version of sourcemeter works with mecoSHARK? The tutorial on Zookeeper crashes with the current version of sourcemeter as depicted here: https://pastebin.com/htCncJhi

**Comment by sherbold** [comment]
We are currently revising all documentation because we are preparing a demo paper. We dropped SourceMeter from the mecoSHARK since 2.0.2 and use OpenStaticAnalyzer instead (basically the same tool, but open source). You can see how to fetch OpenStaticAnalyzer and where it needs to be put in the [install.sh](../blob/master/plugin_packaging/install.sh) script we use in the ServerSHARK to configure the mecoSHARK.

**Comment by sherbold** [comment]
Addressed by a065193
